trigger:
  branches:
    include:
      - main

pool:
  name: 'Self-hosted'  # Must match the name of your agent pool

variables:
  buildConfiguration: 'Release'

steps:
# Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# Restore dependencies (pointing to the solution file location)
- script: dotnet restore ./Lab4/ClassLibraryProjects.sln
  displayName: 'Restore dependencies'

# Build the solution (pointing to the solution file location)
- script: dotnet build ./Lab4/ClassLibraryProjects.sln --configuration $(buildConfiguration)
  displayName: 'Build project'

# Pack the NuGet package (pointing to the solution file location)
- script: dotnet pack ./Lab4/ClassLibraryProjects.sln --configuration $(buildConfiguration) --output ./nupkgs
  displayName: 'Pack NuGet package'

# Authenticate with Azure Artifacts
- task: NuGetAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'

# Push the NuGet package to Azure Artifacts (source feed URL)
- script: dotnet nuget push ./nupkgs/*.nupkg --source "https://pkgs.dev.azure.com/nimani3/Lab4/_packaging/Lab4/nuget/v3/index.json" --api-key AzureArtifacts
  displayName: 'Push to Azure Artifacts'
